const vocab2 = [
  { kr: 'ㅂ'},
  { kr: 'ㅈ'},
  { kr: 'ㄷ'},
  { kr: 'ㄱ'},
  { kr: 'ㅅ'},
  { kr: 'ㅛ'},
  { kr: 'ㅕ'},
  { kr: 'ㅑ'},
  { kr: 'ㅐ'},
  { kr: 'ㅔ'},
  { kr: 'ㅁ'},
  { kr: 'ㄴ'},
  { kr: 'ㅇ'},
  { kr: 'ㄹ'},
  { kr: 'ㅎ'},
  { kr: 'ㅗ'},
  { kr: 'ㅓ'},
  { kr: 'ㅏ'},
  { kr: 'ㅣ'},
  { kr: 'ㅋ'},
  { kr: 'ㅌ'},
  { kr: 'ㅊ'},
  { kr: 'ㅍ'},
  { kr: 'ㅠ'},
  { kr: 'ㅜ'},
  { kr: 'ㅡ'},
  { kr: 'ㅃ'},
  { kr: 'ㅉ'},
  { kr: 'ㄸ'},
  { kr: 'ㄲ'},
  { kr: 'ㅆ'},
  { kr: 'ㅒ'},
  { kr: 'ㅖ'}
];

const vocab = [
  { kr: '은비', en: 'Eunbi'},
  { kr: '사쿠라', en: 'Sakura'},
  { kr: '혜원', en: 'Hyewon'},
  { kr: '예나', en: 'Yena'},
  { kr: '채연', en: 'Chaeyeon'},
  { kr: '채원', en: 'Chaewon'},
  { kr: '민주', en: 'Minju'},
  { kr: '나코', en: 'Nako'},
  { kr: '히토미', en: 'Hitomi'},
  { kr: '유리', en: 'Yuri'},
  { kr: '유진', en: 'Yujin'},
  { kr: '원영', en: 'Wonyoung'}
];