const vocab = [
  { kr: 'ㅂ', en: ''},
  { kr: 'ㅈ', en: ''},
  { kr: 'ㄷ', en: ''},
  { kr: 'ㄱ', en: ''},
  { kr: 'ㅅ', en: ''},
  { kr: 'ㅛ', en: ''},
  { kr: 'ㅕ', en: ''},
  { kr: 'ㅑ', en: ''},
  { kr: 'ㅐ', en: ''},
  { kr: 'ㅔ', en: ''},
  { kr: 'ㅁ', en: ''},
  { kr: 'ㄴ', en: ''},
  { kr: 'ㅇ', en: ''},
  { kr: 'ㄹ', en: ''},
  { kr: 'ㅎ', en: ''},
  { kr: 'ㅗ', en: ''},
  { kr: 'ㅓ', en: ''},
  { kr: 'ㅏ', en: ''},
  { kr: 'ㅣ', en: ''},
  { kr: 'ㅋ', en: ''},
  { kr: 'ㅌ', en: ''},
  { kr: 'ㅊ', en: ''},
  { kr: 'ㅍ', en: ''},
  { kr: 'ㅠ', en: ''},
  { kr: 'ㅜ', en: ''},
  { kr: 'ㅡ', en: ''},
  { kr: 'ㅃ', en: ''},
  { kr: 'ㅉ', en: ''},
  { kr: 'ㄸ', en: ''},
  { kr: 'ㄲ', en: ''},
  { kr: 'ㅆ', en: ''},
  { kr: 'ㅒ', en: ''},
  { kr: 'ㅖ', en: ''}
];

const vocab2 = [
  { kr: '은비', en: 'Eunbi'},
  { kr: '사쿠라', en: 'Sakura'},
  { kr: '혜원', en: 'Hyewon'},
  { kr: '예나', en: 'Yena'},
  { kr: '채연', en: 'Chaeyeon'},
  { kr: '채원', en: 'Chaewon'},
  { kr: '민주', en: 'Minju'},
  { kr: '나코', en: 'Nako'},
  { kr: '히토미', en: 'Hitomi'},
  { kr: '유리', en: 'Yuri'},
  { kr: '유진', en: 'Yujin'},
  { kr: '원영', en: 'Wonyoung'}
];